package com.example.myapplication;

import android.content.Context;
import android.content.Intent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import java.util.List;

/**
 * Adapter class for displaying a list of BlogPost items in a RecyclerView.
 * Holder generated by AI
 */
public class BlogPostAdapter extends RecyclerView.Adapter<BlogPostAdapter.BlogViewHolder> {

    private List<BlogPost> blogList;
    private Context context;
    private BlogFirebaseData blogFirebaseData = new BlogFirebaseData();

    /**
     * Constructs a new instance of BlogPostAdapter.
     *
     * @param context The application context.
     * @param blogList The list of blog posts to display.
     */
    public BlogPostAdapter(Context context, List<BlogPost> blogList) {
        this.context = context;
        this.blogList = blogList;
    }

    @NonNull
    @Override
    /**
     * Inflates the blog item layout and returns a new ViewHolder.
     */
    public BlogViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context).inflate(R.layout.blog_item, parent, false);
        return new BlogViewHolder(view);
    }

    @Override
    /**
     * Binds the data to the ViewHolder.
     */
    public void onBindViewHolder(@NonNull BlogViewHolder holder, int position) {
        BlogPost currentBlog = blogList.get(position);
        holder.titleTextView.setText(currentBlog.getTitle());

        // Set up delete functionality
        holder.deleteButton.setOnClickListener(v -> {
            blogFirebaseData.open();
            BlogPost blogPostToDelete = blogList.get(position);
            blogFirebaseData.deleteBlog(blogPostToDelete);
            notifyDataSetChanged();
        });

        // Set up click listener for detailed view
        holder.itemView.setOnClickListener(v -> {
            Intent intent = new Intent(context, BlogDetailActivity.class);
            intent.putExtra("title", currentBlog.getTitle());
            intent.putExtra("body", currentBlog.getBody());
            context.startActivity(intent);
        });
    }

    @Override
    /**
     * Returns the number of blog posts.
     */
    public int getItemCount() {
        return blogList.size();
    }

    /**
     * Updates the list of blog posts displayed by the adapter.
     *
     * @param blogs The updated list of blog posts.
     */
    public void setBlogs(List<BlogPost> blogs) {
        this.blogList = blogs;
        notifyDataSetChanged();
    }

    /**
     * ViewHolder class to represent individual blog post items.
     */
    static class BlogViewHolder extends RecyclerView.ViewHolder {

        TextView titleTextView;
        TextView bodyTextView;
        Button deleteButton;

        /**
         * Constructs a new instance of BlogViewHolder.
         *
         * @param itemView The individual blog post item view.
         */
        public BlogViewHolder(@NonNull View itemView) {
            super(itemView);
            titleTextView = itemView.findViewById(R.id.blog_title);
            deleteButton = itemView.findViewById(R.id.delete_button);
        }
    }
}
