package com.example.myapplication;

import android.content.Intent;
import android.os.Bundle;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.bottomnavigation.BottomNavigationView;

/**
 * Represents the detailed view of a blog post within the application.
 * Bottom Navigation code generated by AI
 */
public class BlogDetailActivity extends AppCompatActivity implements BlogDetailPresenter.View {

    private TextView titleTextView;
    private TextView bodyTextView;
    private BlogDetailPresenter blogDetailPresenter;

    /**
     * Initializes the activity, sets up the UI components, and displays the blog details.
     *
     * @param savedInstanceState Contains the most recently supplied data. Null if this is the first creation of the activity.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_blog_detail);

        titleTextView = findViewById(R.id.detail_title);
        bodyTextView = findViewById(R.id.detail_body);

        blogDetailPresenter = new BlogDetailPresenter(this);
        blogDetailPresenter.displayBlogDetail(getIntent());

        BottomNavigationView bottomNav = findViewById(R.id.bottom_navigation);
        bottomNav.setOnItemSelectedListener(item -> {
            int itemId = item.getItemId();
            blogDetailPresenter.handleNavigationItemSelected(itemId);
            return true;
        });
    }

    /**
     * Updates the UI with the provided blog details.
     *
     * @param title The title of the blog to be displayed.
     * @param body  The body content of the blog to be displayed.
     */
    @Override
    public void displayBlog(String title, String body) {
        titleTextView.setText(title);
        bodyTextView.setText(body);
    }
}