package com.example.myapplication;

import android.content.Intent;
import android.os.Bundle;
import android.widget.Button;
import android.widget.EditText;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.bottomnavigation.BottomNavigationView;

/**
 * Activity to facilitate the creation of a new blog post.
 * Presenter integration generated by AI
 */
public class CreateBlogActivity extends AppCompatActivity implements CreateBlogPresenter.View {

    private EditText titleEditText, bodyEditText;
    private Button postButton;
    private CreateBlogPresenter createBlogPresenter;

    @Override
    /**
     * Initializes the activity, sets up views, and event listeners.
     */
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create);

        titleEditText = findViewById(R.id.title_edit_text);
        bodyEditText = findViewById(R.id.body_edit_text);
        postButton = findViewById(R.id.post_button);

        createBlogPresenter = new CreateBlogPresenter(this, new BlogFirebaseData());

        // Set up post button click listener
        postButton.setOnClickListener(v -> {
            createBlogPresenter.onPostButtonClicked(
                    titleEditText.getText().toString(),
                    bodyEditText.getText().toString()
            );
        });

        // Set up bottom navigation
        BottomNavigationView bottomNav = findViewById(R.id.bottom_navigation);
        bottomNav.setOnItemSelectedListener(item -> {
            int itemId = item.getItemId();

            if (itemId == R.id.nav_home) {
                createBlogPresenter.onHomeNavigationSelected();
            } else if (itemId == R.id.nav_add_blog) {
                createBlogPresenter.onAddBlogNavigationSelected();
            }

            return true;
        });
    }

    @Override
    /**
     * Closes the current activity.
     */
    public void closeActivity() {
        finish();
    }
}
